/**
 * Extended database schema exports
 * Includes new bonus score change reason tracking
 * This supplements the autogenerated schema index without modifying it
 */

// Export existing schemas (re-export for convenience)
export * from './index';

// Export new bonus score change reason schema
export {default as BonusScoreChangeReason} from './bonus_score_change_reason';
export type {BonusScoreChangeReason_InsertParameters, BonusScoreChangeReasonQuery} from './bonus_score_change_reason';
